### ISSUE TITLE
Opengl 3.0 compatibility

### ISSUE THREAD

**Issue by Prathik-Jain** [dgranosa/liveW#1]
Please update README on how to set it up!

**Comment by dgranosa** [comment]
It's updated, if you have any questions just ask.

**Comment by Prathik-Jain** [comment]
Waiting for the Shadertoy

**Comment by dgranosa** [comment]
It's up.

**Comment by Prathik-Jain** [comment]
Thanks. Tried using the same shader as yours. 
![image](https://user-images.githubusercontent.com/25041441/40500369-1b24ee2c-5fa2-11e8-94d2-0d127c5911df.png)
This is what I get - Everything's wrong!
I would be great if you share your `frag.glsl`

**Comment by dgranosa** [comment]
Shader is inside Shaders folder. To tell program to run that particular shader you need to pass argument **-p equalizer**.

**Comment by Prathik-Jain** [comment]
Equalizer also gives similar output - with off colors

**Comment by Prathik-Jain** [comment]
The program also says 
`Couldn't load vertex file using default code`
I hope this is not a problem!

**Comment by dgranosa** [comment]
It's not.

**Comment by dgranosa** [comment]
Which version of opengl do you have? It looks like it doesn't support older versions of opengl.
`glxinfo | grep "version"`

**Comment by Prathik-Jain** [comment]
```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.4
OpenGL core profile shading language version string: 4.50
OpenGL version string: 3.0 Mesa 18.0.4
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.0.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by dgranosa** [comment]
It looks like it doesn't work properly for opengl 3. I'm working on it to fix it.

**Comment by Prathik-Jain** [comment]
Waiting!

**Comment by dgranosa** [comment]
It should work now.

**Comment by Prathik-Jain** [comment]
It does - I think the transparency is the issue now.
tired 
`./liveW -s alsa_output.pci-0000_00_1f.3.analog-stereo.monitor -p equalizer -t 0.5 `
but its fully opaque.

**Comment by dgranosa** [comment]
Do you have compton running?

**Comment by Prathik-Jain** [comment]
So sorry, completely forgot about that!

**Comment by Prathik-Jain** [comment]
Also, I use a dual monitor setup - yet I want to run it on a single monitor only. Any way I can do that?

**Comment by dgranosa** [comment]
I'm still working on it.

**Comment by dgranosa** [comment]
Update is up, everything is explained in README how to set it up. If you have more questions make new issue.
