### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by dillasyx** [dgranosa/liveW#5]
I just tried to use this on my Arch Linux with i3.
I've installed everything except Playerctl.
Everytime I try to start it I get an Segmentation fault.
Debug-Message:

> Desktop window (152) is root window
>Window depth 32, 3840x1200
>OpenGL:
>        vendor Intel Open Source Technology Center
>        renderer Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2) 
>        version 4.5 (Core Profile) Mesa 19.0.5
>        shader language 4.50
>Extension "GL_ARB_compute_shader" found
>Couldn't load vertex file using default code
>device = alsa_output.pci-0000_00_1b.0.analog-stereo.monitor
>Segmentation fault (core dumped)

**Comment by dgranosa** [comment]
Thanks for reporting the issue, but can you try find where it crashes. You can do it with GDB.
If you are not familiar with GDB here are some commands:
```
gdb liveW
run
*when it crashes*
bt
```

**Comment by dillasyx** [comment]
I hope this is correct:

![DeepinScreenshot_select-area_20190606133319](https://user-images.githubusercontent.com/11612223/59029861-b74c1c80-885f-11e9-9172-ed613bbd8190.png)

**Comment by dgranosa** [comment]
Issue is fixed in: 5e44544d3978b7b7bb53f353d14ea399bbdfbb99

It should be working now. Can you confirm from your side?

**Comment by dillasyx** [comment]
Yeah no seg fault anymore, thanks.
